### ISSUE TITLE
make it also work with promises

### ISSUE THREAD

**Issue by phra** [staltz/promisify-tuple#2]
you can benefit from this _return-tuple_ approach also with vanilla promises. (_as seen on_ https://github.com/phra/await-to-ts)

i suggest to implement an unique library that can handle in first place promises and then falls back to call `util.promisify()` under the hood.

imho it's also worth it to evalute if the `await-to` construct should be integrated in ES specs.

what do you think about it?

thanks.

ps: it would be also nice to make it typescript-friendly.

**Comment by staltz** [comment]
> you can benefit from this return-tuple approach also with vanilla promises.

Yes, great point, but that could be built as a separate library (libraries are cheap!), which could even use this one as a dependency. Given the very clear purpose in the readme, it would be odd to also do something else, polymorphically.

> ps: it would be also nice to make it typescript-friendly.

TypeScript is supported :)
